# Generated by Django 4.2.20 on 2025-03-25 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('start_time', models.DateTimeField(verbose_name='Czas rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Czas zakończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Link do spotkania')),
                ('room_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod pokoju')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organizator')),
            ],
            options={
                'verbose_name': 'Spotkanie',
                'verbose_name_plural': 'Spotkania',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Zaproszony'), ('accepted', 'Zaakceptował'), ('declined', 'Odrzucił'), ('tentative', 'Niepewny')], default='invited', max_length=10, verbose_name='Status')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zaproszenia')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='Data odpowiedzi')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uczestnik spotkania',
                'verbose_name_plural': 'Uczestnicy spotkania',
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Uczestnicy'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_before', models.IntegerField(choices=[(5, '5 minut'), (10, '10 minut'), (15, '15 minut'), (30, '30 minut'), (60, '1 godzina'), (120, '2 godziny'), (1440, '1 dzień')], default=15, verbose_name='Czas przypomnienia')),
                ('sent', models.BooleanField(default=False, verbose_name='Wysłano')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przypomnienie',
                'verbose_name_plural': 'Przypomnienia',
                'unique_together': {('meeting', 'user', 'minutes_before')},
            },
        ),
    ]
