# Generated by Django 4.2.20 on 2025-03-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktywne'),
        ),
    ]
